### ISSUE TITLE
New methods: Named parameters vs. argument hash

### ISSUE THREAD

**Issue by jamonholmgren** [kemiller/rubymotion-style-guide#1]
Example:

``` ruby
# Named parameters
def my_method(my_title, with_size: my_size)
  # ...
end

# Argument hash
def my_method(args={})
  # ...
end
```

I prefer the argument hash.

**Comment by kemiller** [comment]
I like argument hash because it's familiar and more flexible.  You can leave args out or reorder them.  

Only place I'd want to use named args is if I'm writing something to look like a initWith... method, but that's another ticket.

**Comment by jamonholmgren** [comment]
I agree.
